GET http://localhost:8090/
Accept: application/json

###

GET http://localhost:8090/api/hello
Accept: application/json

###

GET http://localhost:8090/api/item/123/camara
Accept: application/json

###

GET http://localhost:8090/api/items/WOLOX/Juan?page=2&per_page=5&sort_by=name
Accept: application/json

###

GET http://localhost:8090/api/itemsMultiple?ids=1,2,3,4
Accept: application/json

###

POST http://localhost:8090/api/person/Globant/Alejandro
Content-Type: application/json

{
    "nombre": "Juan Carlos",
    "edad": 39,
    "saldo": 1500.50
}




